In [65]:
import pandas as pd

In [66]:
data = pd.read_csv("data/characters.csv")

In [67]:
data.head()

,mal_id,name,name_kanji,nicknames,favorites,about,main_picture,url
0,417,Lelouch Lamperouge,ルルーシュ・ランペルージ,"['Lelouch vi Britannia', 'Zero', 'Lulu', 'Blac...",156066,"Age: 17 (first season), 18 (second season)\nDa...",https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/417/Lelouch_...
1,45627,Levi,リヴァイ,[],130849,"Birthday: December 25\nHeight: 160 cm (5'3"")\n...",https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/45627/Levi
2,71,L Lawliet,エル ローライト,"['Ryuga Hideki', 'Ryuzaki', 'Eraldo Coil', 'De...",119353,"Birthday: October 31, 1979 (1982 in anime)\nZo...",https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/71/L_Lawliet
3,40,Luffy Monkey D.,モンキー・D・ルフィ,"['Mugiwara', 'Straw Hat', 'Lucy', 'Luffytaro']",118163,"Age: 17; 19\nBirthdate: May 5, Taurus\nHeight:...",https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/40/Luffy_Mon...
4,62,Zoro Roronoa,ロロノア・ゾロ,"['Pirate Hunter', 'Marimo', 'Zorojuro', 'King ...",94312,"Age: 19; 21\nBirthdate: November 11, Scorpio \...",https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/62/Zoro_Roronoa

In [68]:
data = data.rename(columns={"mal_id": "character_id"})
data = data.rename(columns={"name": "character_name"})
data

,character_id,character_name,name_kanji,nicknames,favorites,about,main_picture,url
0,417,Lelouch Lamperouge,ルルーシュ・ランペルージ,"['Lelouch vi Britannia', 'Zero', 'Lulu', 'Blac...",156066,"Age: 17 (first season), 18 (second season)\nDa...",https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/417/Lelouch_...
1,45627,Levi,リヴァイ,[],130849,"Birthday: December 25\nHeight: 160 cm (5'3"")\n...",https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/45627/Levi
2,71,L Lawliet,エル ローライト,"['Ryuga Hideki', 'Ryuzaki', 'Eraldo Coil', 'De...",119353,"Birthday: October 31, 1979 (1982 in anime)\nZo...",https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/71/L_Lawliet
3,40,Luffy Monkey D.,モンキー・D・ルフィ,"['Mugiwara', 'Straw Hat', 'Lucy', 'Luffytaro']",118163,"Age: 17; 19\nBirthdate: May 5, Taurus\nHeight:...",https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/40/Luffy_Mon...
4,62,Zoro Roronoa,ロロノア・ゾロ,"['Pirate Hunter', 'Marimo', 'Zorojuro', 'King ...",94312,"Age: 19; 21\nBirthdate: November 11, Scorpio \...",https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/62/Zoro_Roronoa
...,...,...,...,...,...,...,...,...
146044,214031,Erika Jiyanome,蛇ノ目 エリカ,[],0,NaN,https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/214031/Erika...
146045,214032,Hibana Kagari,篝 ヒバナ,[],0,NaN,https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/214032/Hiban...
146046,214044,Cashel,カシェル,[],0,NaN,https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/214044/Cashel
146047,214045,Raj,ラジ,[],0,NaN,https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/214045/Raj
146048,214046,Gimul,ギムル,[],0,NaN,https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/214046/Gimul

In [69]:
cols_to_drop = [
    "favorites",
    "about",
    "episodes",
]

data = data.drop(columns=[c for c in cols_to_drop if c in data.columns])
data

,character_id,character_name,name_kanji,nicknames,main_picture,url
0,417,Lelouch Lamperouge,ルルーシュ・ランペルージ,"['Lelouch vi Britannia', 'Zero', 'Lulu', 'Blac...",https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/417/Lelouch_...
1,45627,Levi,リヴァイ,[],https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/45627/Levi
2,71,L Lawliet,エル ローライト,"['Ryuga Hideki', 'Ryuzaki', 'Eraldo Coil', 'De...",https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/71/L_Lawliet
3,40,Luffy Monkey D.,モンキー・D・ルフィ,"['Mugiwara', 'Straw Hat', 'Lucy', 'Luffytaro']",https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/40/Luffy_Mon...
4,62,Zoro Roronoa,ロロノア・ゾロ,"['Pirate Hunter', 'Marimo', 'Zorojuro', 'King ...",https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/62/Zoro_Roronoa
...,...,...,...,...,...,...
146044,214031,Erika Jiyanome,蛇ノ目 エリカ,[],https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/214031/Erika...
146045,214032,Hibana Kagari,篝 ヒバナ,[],https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/214032/Hiban...
146046,214044,Cashel,カシェル,[],https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/214044/Cashel
146047,214045,Raj,ラジ,[],https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/214045/Raj
146048,214046,Gimul,ギムル,[],https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/214046/Gimul

In [70]:
idx = data.columns.get_loc("character_name") + 1
data.insert(idx, "claimed_by", -1)
data

,character_id,character_name,claimed_by,name_kanji,nicknames,main_picture,url
0,417,Lelouch Lamperouge,-1,ルルーシュ・ランペルージ,"['Lelouch vi Britannia', 'Zero', 'Lulu', 'Blac...",https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/417/Lelouch_...
1,45627,Levi,-1,リヴァイ,[],https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/45627/Levi
2,71,L Lawliet,-1,エル ローライト,"['Ryuga Hideki', 'Ryuzaki', 'Eraldo Coil', 'De...",https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/71/L_Lawliet
3,40,Luffy Monkey D.,-1,モンキー・D・ルフィ,"['Mugiwara', 'Straw Hat', 'Lucy', 'Luffytaro']",https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/40/Luffy_Mon...
4,62,Zoro Roronoa,-1,ロロノア・ゾロ,"['Pirate Hunter', 'Marimo', 'Zorojuro', 'King ...",https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/62/Zoro_Roronoa
...,...,...,...,...,...,...,...
146044,214031,Erika Jiyanome,-1,蛇ノ目 エリカ,[],https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/214031/Erika...
146045,214032,Hibana Kagari,-1,篝 ヒバナ,[],https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/214032/Hiban...
146046,214044,Cashel,-1,カシェル,[],https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/214044/Cashel
146047,214045,Raj,-1,ラジ,[],https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/214045/Raj
146048,214046,Gimul,-1,ギムル,[],https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/214046/Gimul

In [71]:
idx = data.columns.get_loc("character_name") + 1
data.insert(idx, "anime_id", -1)
data

,character_id,character_name,anime_id,claimed_by,name_kanji,nicknames,main_picture,url
0,417,Lelouch Lamperouge,-1,-1,ルルーシュ・ランペルージ,"['Lelouch vi Britannia', 'Zero', 'Lulu', 'Blac...",https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/417/Lelouch_...
1,45627,Levi,-1,-1,リヴァイ,[],https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/45627/Levi
2,71,L Lawliet,-1,-1,エル ローライト,"['Ryuga Hideki', 'Ryuzaki', 'Eraldo Coil', 'De...",https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/71/L_Lawliet
3,40,Luffy Monkey D.,-1,-1,モンキー・D・ルフィ,"['Mugiwara', 'Straw Hat', 'Lucy', 'Luffytaro']",https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/40/Luffy_Mon...
4,62,Zoro Roronoa,-1,-1,ロロノア・ゾロ,"['Pirate Hunter', 'Marimo', 'Zorojuro', 'King ...",https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/62/Zoro_Roronoa
...,...,...,...,...,...,...,...,...
146044,214031,Erika Jiyanome,-1,-1,蛇ノ目 エリカ,[],https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/214031/Erika...
146045,214032,Hibana Kagari,-1,-1,篝 ヒバナ,[],https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/214032/Hiban...
146046,214044,Cashel,-1,-1,カシェル,[],https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/214044/Cashel
146047,214045,Raj,-1,-1,ラジ,[],https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/214045/Raj
146048,214046,Gimul,-1,-1,ギムル,[],https://cdn.myanimelist.net/images/characters/...,https://myanimelist.net/character/214046/Gimul

In [72]:
null_count = data["url"].isnull().sum()
null_count

np.int64(0)

In [73]:
excess_duplicates = data[data.duplicated(subset=["character_id"])]
excess_duplicates[["character_id", "character_name"]]

Empty DataFrame
Columns: [character_id, character_name]
Index: []

In [74]:
print(data.dtypes)

character_id      int64
character_name      str
anime_id          int64
claimed_by        int64
name_kanji          str
nicknames           str
main_picture        str
url                 str
dtype: object

In [75]:
data.to_csv("data/characters_cleaned.csv", index=False)