In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("../data/anime.csv")

In [64]:
data.head()

,mal_id,title,type,score,scored_by,status,episodes,aired_from,aired_to,source,...,producers,licensors,synopsis,background,main_picture,url,trailer_url,title_english,title_japanese,title_synonyms
0,5114,Fullmetal Alchemist: Brotherhood,TV,9.13,1867867.0,Finished Airing,64.0,2009-04-05,2010-07-04,Manga,...,"['Aniplex', 'Square Enix', 'Mainichi Broadcast...","['Funimation', 'Aniplex of America']",After a horrific alchemy experiment goes wrong...,NaN,https://cdn.myanimelist.net/images/anime/1223/...,https://myanimelist.net/anime/5114/Fullmetal_A...,https://www.youtube.com/watch?v=--IcmZkvL0Q,Fullmetal Alchemist: Brotherhood,鋼の錬金術師 FULLMETAL ALCHEMIST,['Hagane no Renkinjutsushi: Fullmetal Alchemis...
1,11061,Hunter x Hunter (2011),TV,9.05,1505975.0,Finished Airing,148.0,2011-10-02,2014-09-24,Manga,...,"['VAP', 'Nippon Television Network', 'Shueisha']",['VIZ Media'],Hunters devote themselves to accomplishing haz...,NaN,https://cdn.myanimelist.net/images/anime/1337/...,https://myanimelist.net/anime/11061/Hunter_x_H...,https://www.youtube.com/watch?v=D9iTQRB4XRk,Hunter x Hunter,HUNTER×HUNTER（ハンター×ハンター）,['HxH (2011)']
2,38524,Shingeki no Kyojin Season 3 Part 2,TV,9.07,1325615.0,Finished Airing,10.0,2019-04-29,2019-07-01,Manga,...,"['Production I.G', 'Dentsu', 'Mainichi Broadca...",['Funimation'],Seeking to restore humanity's diminishing hope...,Shingeki no Kyojin adapts content from volumes...,https://cdn.myanimelist.net/images/anime/1517/...,https://myanimelist.net/anime/38524/Shingeki_n...,https://www.youtube.com/watch?v=hKHepjfj5Tw,Attack on Titan Season 3 Part 2,進撃の巨人 Season3 Part.2,[]
3,9253,Steins;Gate,TV,9.08,1250089.0,Finished Airing,24.0,2011-04-06,2011-09-14,Visual novel,...,"['Frontier Works', 'Media Factory', 'Movic', '...",['Funimation'],Eccentric scientist Rintarou Okabe has a never...,Steins;Gate is based on 5pb. and Nitroplus' re...,https://cdn.myanimelist.net/images/anime/5/731...,https://myanimelist.net/anime/9253/Steins_Gate,https://www.youtube.com/watch?v=27OZc-ku6is,Steins;Gate,STEINS;GATE,[]
4,28851,Koe no Katachi,Movie,8.95,1395593.0,Finished Airing,1.0,2016-09-17,NaN,Manga,...,"['Shochiku', 'Pony Canyon', 'Kodansha', 'ABC A...","['Eleven Arts', 'NYAV Post']","As a wild youth, elementary school student Sho...",Winner of the Excellence Award on the 20th Jap...,https://cdn.myanimelist.net/images/anime/1122/...,https://myanimelist.net/anime/28851/Koe_no_Kat...,https://www.youtube.com/watch?v=XBNWo25izJ8,A Silent Voice,聲の形,['The Shape of Voice']

In [65]:
data = data.rename(columns={"mal_id": "anime_id"})
data = data.rename(columns={"title": "anime_name"})

data

,anime_id,anime_name,type,score,scored_by,status,episodes,aired_from,aired_to,source,...,producers,licensors,synopsis,background,main_picture,url,trailer_url,title_english,title_japanese,title_synonyms
0,5114,Fullmetal Alchemist: Brotherhood,TV,9.13,1867867.0,Finished Airing,64.0,2009-04-05,2010-07-04,Manga,...,"['Aniplex', 'Square Enix', 'Mainichi Broadcast...","['Funimation', 'Aniplex of America']",After a horrific alchemy experiment goes wrong...,NaN,https://cdn.myanimelist.net/images/anime/1223/...,https://myanimelist.net/anime/5114/Fullmetal_A...,https://www.youtube.com/watch?v=--IcmZkvL0Q,Fullmetal Alchemist: Brotherhood,鋼の錬金術師 FULLMETAL ALCHEMIST,['Hagane no Renkinjutsushi: Fullmetal Alchemis...
1,11061,Hunter x Hunter (2011),TV,9.05,1505975.0,Finished Airing,148.0,2011-10-02,2014-09-24,Manga,...,"['VAP', 'Nippon Television Network', 'Shueisha']",['VIZ Media'],Hunters devote themselves to accomplishing haz...,NaN,https://cdn.myanimelist.net/images/anime/1337/...,https://myanimelist.net/anime/11061/Hunter_x_H...,https://www.youtube.com/watch?v=D9iTQRB4XRk,Hunter x Hunter,HUNTER×HUNTER（ハンター×ハンター）,['HxH (2011)']
2,38524,Shingeki no Kyojin Season 3 Part 2,TV,9.07,1325615.0,Finished Airing,10.0,2019-04-29,2019-07-01,Manga,...,"['Production I.G', 'Dentsu', 'Mainichi Broadca...",['Funimation'],Seeking to restore humanity's diminishing hope...,Shingeki no Kyojin adapts content from volumes...,https://cdn.myanimelist.net/images/anime/1517/...,https://myanimelist.net/anime/38524/Shingeki_n...,https://www.youtube.com/watch?v=hKHepjfj5Tw,Attack on Titan Season 3 Part 2,進撃の巨人 Season3 Part.2,[]
3,9253,Steins;Gate,TV,9.08,1250089.0,Finished Airing,24.0,2011-04-06,2011-09-14,Visual novel,...,"['Frontier Works', 'Media Factory', 'Movic', '...",['Funimation'],Eccentric scientist Rintarou Okabe has a never...,Steins;Gate is based on 5pb. and Nitroplus' re...,https://cdn.myanimelist.net/images/anime/5/731...,https://myanimelist.net/anime/9253/Steins_Gate,https://www.youtube.com/watch?v=27OZc-ku6is,Steins;Gate,STEINS;GATE,[]
4,28851,Koe no Katachi,Movie,8.95,1395593.0,Finished Airing,1.0,2016-09-17,NaN,Manga,...,"['Shochiku', 'Pony Canyon', 'Kodansha', 'ABC A...","['Eleven Arts', 'NYAV Post']","As a wild youth, elementary school student Sho...",Winner of the Excellence Award on the 20th Jap...,https://cdn.myanimelist.net/images/anime/1122/...,https://myanimelist.net/anime/28851/Koe_no_Kat...,https://www.youtube.com/watch?v=XBNWo25izJ8,A Silent Voice,聲の形,['The Shape of Voice']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24635,52415,Castlevania,TV,NaN,NaN,Finished Airing,32.0,2017-07-07,2021-05-01,Game,...,[],[],"Inspired by the popular video game series, thi...",Castlevania is an American adult animated dark...,NaN,https://myanimelist.net/anime/52415/Castlevania,NaN,Castlevania,Akumajō Dracula,[]
24636,52416,Geheime Welt Idhún Staffel 1,TV,NaN,NaN,Finished Airing,5.0,2021-08-01,2021-10-01,NaN,...,[],[],Der Totenbeschwörer Ashran hat die Macht in Id...,NaN,NaN,https://myanimelist.net/anime/52416/Geheime_We...,NaN,NaN,NaN,[]
24637,52417,Mayumi,Movie,NaN,NaN,Finished Airing,1.0,2016-01-01,NaN,Original,...,[],[],Mayumi is a spoiled girl whose parents buy her...,"1st year work 2016 by Chinami Taniguchi, Tokyo...",https://cdn.myanimelist.net/images/anime/1989/...,https://myanimelist.net/anime/52417/Mayumi,NaN,Mayumi,まゆみ,[]
24638,52418,Bremen,Music,NaN,NaN,Finished Airing,1.0,2022-07-04,NaN,NaN,...,[],[],Music video for the song Bremen by Yorushika.,NaN,NaN,https://myanimelist.net/anime/52418/Bremen,NaN,NaN,ブレーメン,[]
24639,52419,Shingeki no Kyojin Movie 3: Kakusei no Houkou,Movie,NaN,NaN,Finished Airing,1.0,NaN,NaN,Manga,...,[],[],NaN,NaN,NaN,https://myanimelist.net/anime/52419/Shingeki_n...,NaN,NaN,Shingeki no Kyojin Movie 3: Kakusei no Houkou,[]

In [66]:
cols_to_drop = [
    "scored_by",
    "status",
    "episodes",
    "aired_from",
    "aired_to",
    "source",
    "producers",
    "licensors",
    "title_synonyms",
    "type",
    "members",
    "favorites",
    "duration",
    "rating",
    "nsfw",
    "themes",
    "demographics",
    "studios",
    "synopsis",
    "background",
    "pending_approval",
    "premiered_season",
    "premiered_year",
    "broadcast_day",
    "broadcast_time"
    
    
    
    
]
data = data.drop(columns=[c for c in cols_to_drop if c in data.columns])
data

,anime_id,anime_name,score,genres,main_picture,url,trailer_url,title_english,title_japanese
0,5114,Fullmetal Alchemist: Brotherhood,9.13,"['Action', 'Adventure', 'Drama', 'Fantasy']",https://cdn.myanimelist.net/images/anime/1223/...,https://myanimelist.net/anime/5114/Fullmetal_A...,https://www.youtube.com/watch?v=--IcmZkvL0Q,Fullmetal Alchemist: Brotherhood,鋼の錬金術師 FULLMETAL ALCHEMIST
1,11061,Hunter x Hunter (2011),9.05,"['Action', 'Adventure', 'Fantasy']",https://cdn.myanimelist.net/images/anime/1337/...,https://myanimelist.net/anime/11061/Hunter_x_H...,https://www.youtube.com/watch?v=D9iTQRB4XRk,Hunter x Hunter,HUNTER×HUNTER（ハンター×ハンター）
2,38524,Shingeki no Kyojin Season 3 Part 2,9.07,"['Action', 'Drama']",https://cdn.myanimelist.net/images/anime/1517/...,https://myanimelist.net/anime/38524/Shingeki_n...,https://www.youtube.com/watch?v=hKHepjfj5Tw,Attack on Titan Season 3 Part 2,進撃の巨人 Season3 Part.2
3,9253,Steins;Gate,9.08,"['Drama', 'Sci-Fi', 'Suspense']",https://cdn.myanimelist.net/images/anime/5/731...,https://myanimelist.net/anime/9253/Steins_Gate,https://www.youtube.com/watch?v=27OZc-ku6is,Steins;Gate,STEINS;GATE
4,28851,Koe no Katachi,8.95,['Drama'],https://cdn.myanimelist.net/images/anime/1122/...,https://myanimelist.net/anime/28851/Koe_no_Kat...,https://www.youtube.com/watch?v=XBNWo25izJ8,A Silent Voice,聲の形
...,...,...,...,...,...,...,...,...,...
24635,52415,Castlevania,NaN,"['Action', 'Adventure', 'Fantasy', 'Horror']",NaN,https://myanimelist.net/anime/52415/Castlevania,NaN,Castlevania,Akumajō Dracula
24636,52416,Geheime Welt Idhún Staffel 1,NaN,"['Action', 'Adventure', 'Supernatural']",NaN,https://myanimelist.net/anime/52416/Geheime_We...,NaN,NaN,NaN
24637,52417,Mayumi,NaN,"['Avant Garde', 'Drama', 'Horror']",https://cdn.myanimelist.net/images/anime/1989/...,https://myanimelist.net/anime/52417/Mayumi,NaN,Mayumi,まゆみ
24638,52418,Bremen,NaN,[],NaN,https://myanimelist.net/anime/52418/Bremen,NaN,NaN,ブレーメン
24639,52419,Shingeki no Kyojin Movie 3: Kakusei no Houkou,NaN,"['Action', 'Drama']",NaN,https://myanimelist.net/anime/52419/Shingeki_n...,NaN,NaN,Shingeki no Kyojin Movie 3: Kakusei no Houkou

In [67]:
null_count = data["url"].isnull().sum()
null_count

np.int64(0)

In [68]:
print(data.dtypes)

anime_id            int64
anime_name            str
score             float64
genres                str
main_picture          str
url                   str
trailer_url           str
title_english         str
title_japanese        str
dtype: object

In [69]:
excess_duplicates = data[data.duplicated(subset=["anime_name"])]

excess_duplicates[["anime_id", "anime_name"]]

       anime_id                  anime_name
17757     41088                Mézga család
17897     41617                 Mushibugyou
17899     41624                    Humanoid
18069     42240                     Refrain
18793     43905          Yisheng Yu Huangdi
...         ...                         ...
24612     52392  Avatar: The last airbender
24621     52401               Fake Identity
24632     52412                 Castlevania
24635     52415                 Castlevania
24638     52418                      Bremen

[249 rows x 2 columns]

In [70]:
data = data.drop_duplicates(subset=["anime_name"])

data.shape

(24391, 9)

In [ ]:
data.to_csv("../data/anime_cleaned.csv", index=False)